set_bms_mode:
  name: Set BMS Working Mode
  description: Sets the working mode of the Hoymiles hybrid inverter.
  target:
    device:
      integration: hoymiles_wifi
  fields:
    bms_mode:
      required: true
      example: self_use
      selector:
        select:
          options:
            - "self_use"
            - "economic"
            - "backup_power"
            - "pure_off_grid"
            - "forced_charging"
            - "forced_discharge"
            - "peak_shaving"
            - "time_of_use"
          translation_key: "bms_mode_type"
    rev_soc:
      required: true
      example: 50
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    max_power:
      required: false
      example: 60
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    peak_soc:
      required: false
      example: 80
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    peak_meter_power:
      required: false
      example: 100
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    time_settings:
      required: false
      example: "01.01-31.03:1,2,3=06:00-10:00-0.20-0.10,00:00-06:00-0.10-0.05,10:00-18:00-0.15-0.08;4,5=07:00-11:00-0.22-0.11,00:00-07:00-0.08-0.04,11:00-17:00-0.14-0.07"
      selector:
        text:
    time_periods:
      required: false
      example: "06:00-08:00-50-90|18:00-20:00-40-20"
      selector:
        text:
